# docker-compose -f postgresql.yaml up -d
services:
  postgres_db:
    container_name: postgres
    image: postgres:16.9
    networks:
      - postgresql
    ports:
      - "${POSTGRES_DB_PORT:-5432}:5432"
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: passwd
      POSTGRES_DB: postgres_db
      PGDATA: /var/lib/postgresqldata/pgdata
    volumes:
      - $HOME/data/postgres_db:/var/lib/postgresql/data
      - "${MYSQL_DATA_DIR:-${HOME}/data/postgres_db}:/var/lib/postgresql/data"
    command: []

networks:
  postgresql:
    name: postgresql
    driver: bridge
